"""empty message

Revision ID: 7bc8d18894ec
Revises: 
Create Date: 2022-10-27 16:41:50.503070

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7bc8d18894ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classifiers',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('parent_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('fields', sa.String(), nullable=False),
    sa.Column('attributes', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CORRUPT', 'DELETE', 'ARCHIVE', name='status'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('parent_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('type', sa.Enum('ADD', 'DELETE', 'UPDATE', 'ADDRECORD', 'UPDATERECORD', 'DELETERECORD', name='typeoperation'), nullable=False),
    sa.Column('rule', sa.String(), nullable=False),
    sa.Column('attributes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('armed_force',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('parent_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('view_vf_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('genus_vf_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('purpose_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('struction_vf_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CORRUPT', 'DELETE', 'ARCHIVE', name='status'), nullable=False),
    sa.ForeignKeyConstraint(['genus_vf_id'], ['classifiers.id'], ),
    sa.ForeignKeyConstraint(['purpose_id'], ['classifiers.id'], ),
    sa.ForeignKeyConstraint(['struction_vf_id'], ['classifiers.id'], ),
    sa.ForeignKeyConstraint(['view_vf_id'], ['classifiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('armed_force')
    op.drop_table('events')
    op.drop_table('classifiers')
    # ### end Alembic commands ###
